model_name: bert

dataset: 
  name: code4ml
  kwargs: 
    path: data/code4ml/markup_data.csv
    marks: [5]
    num_classes: 65

train_marks: [4] # use only for train, for val and test only mark 5 data is used
additional_data: null

optimizer:
  name: AdamW
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: 1
batch_size: 8
seed: 42
run_id: markup_data_bert_on_5