model_name: codebert

dataset: 
  name: code4ml
  kwargs: 
    path: data/code4ml/markup_data.csv
    marks: [5]
    num_classes: 88

train_marks: [4] # use only for train, for val and test only mark 5 data is used
additional_data: null

optimizer:
  name: AdamW
  kwargs:
    lr: 0.00005
num_epochs: 50
batch_size: 32
seed: 42
run_id: markup_data_codebert_on_4