model_name: codebert

dataset: 
  name: code4ml
  kwargs: 
    path: data/code4ml/markup_data.csv
    marks: [5]
    num_classes: 65

train_marks: [] # use only for train, for val and test only mark 5 data is used
additional_data: data/code4ml/after_split_data.csv

optimizer:
  name: AdamW
  kwargs:
    lr: 0.00005
scheduler: null
num_epochs: 20
batch_size: 8
seed: 42
run_id: markup_data_codebert_on_5